import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "../ui/globals.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";
import { montserrat } from "@/ui/fonts";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" >
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={`flex flex-col w-full justify-center items-center ${montserrat.className} antialiased bg-gradient-to-r from-[#174173] to-[#226197] p-2 border `} >
        <Providers>
          <Navbar />
          <h1 className="text-center">this is the app layout</h1>
          {children}
        </Providers>
      </body>
    </html >
  );
}
